# Generated by Django 5.2.4 on 2025-07-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_authuser_date_joined_alter_authuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cartegory',
            field=models.CharField(default='w', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authuser',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
